export const coursesData = [
  {
    id: 1,
    title: "AI-Powered Web Development Masterclass",
    instructor: "Sarah Johnson",
    instructorAvatar: "/placeholder-c7d3i.png",
    price: 99.99,
    originalPrice: 149.99,
    rating: 4.8,
    students: 12543,
    duration: "42 hours",
    level: "Intermediate",
    category: "Web Development",
    thumbnail: "/placeholder-9zvtf.png",
    description:
      "Master modern web development with AI tools and techniques. Learn React, Node.js, and AI integration.",
    features: [
      "AI-assisted coding techniques",
      "React 18 with latest features",
      "Node.js backend development",
      "AI chatbot integration",
      "Real-world projects",
    ],
    curriculum: [
      { module: "Introduction to AI in Web Development", duration: "2 hours" },
      { module: "React Fundamentals with AI Tools", duration: "8 hours" },
      { module: "Backend Development with Node.js", duration: "10 hours" },
      { module: "AI Integration and APIs", duration: "12 hours" },
      { module: "Deployment and Production", duration: "6 hours" },
      { module: "Advanced AI Features", duration: "4 hours" },
    ],
    isAIRecommended: true,
    tags: ["React", "Node.js", "AI", "JavaScript", "Full Stack"],
  },
  {
    id: 2,
    title: "Machine Learning for Beginners",
    instructor: "Dr. Michael Chen",
    instructorAvatar: "/placeholder-za5kk.png",
    price: 79.99,
    originalPrice: 119.99,
    rating: 4.9,
    students: 8765,
    duration: "35 hours",
    level: "Beginner",
    category: "Machine Learning",
    thumbnail: "/placeholder-bsvoc.png",
    description:
      "Start your ML journey with hands-on projects and real-world applications. No prior experience needed.",
    features: [
      "Python programming basics",
      "Supervised & Unsupervised Learning",
      "Neural Networks introduction",
      "Hands-on projects",
      "Industry case studies",
    ],
    curriculum: [
      { module: "Python for ML", duration: "6 hours" },
      { module: "Data Preprocessing", duration: "5 hours" },
      { module: "Supervised Learning", duration: "10 hours" },
      { module: "Unsupervised Learning", duration: "8 hours" },
      { module: "Neural Networks Basics", duration: "6 hours" },
    ],
    isAIRecommended: true,
    tags: ["Python", "Machine Learning", "Data Science", "AI"],
  },
  {
    id: 3,
    title: "Advanced React with TypeScript",
    instructor: "Emily Rodriguez",
    instructorAvatar: "/placeholder-hea8t.png",
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.7,
    students: 6432,
    duration: "28 hours",
    level: "Advanced",
    category: "Frontend Development",
    thumbnail: "/placeholder-evz2b.png",
    description:
      "Take your React skills to the next level with TypeScript, advanced patterns, and performance optimization.",
    features: [
      "TypeScript integration",
      "Advanced React patterns",
      "Performance optimization",
      "Testing strategies",
      "State management",
    ],
    curriculum: [
      { module: "TypeScript Fundamentals", duration: "4 hours" },
      { module: "Advanced React Patterns", duration: "8 hours" },
      { module: "Performance Optimization", duration: "6 hours" },
      { module: "Testing with Jest & RTL", duration: "5 hours" },
      { module: "State Management Solutions", duration: "5 hours" },
    ],
    isAIRecommended: false,
    tags: ["React", "TypeScript", "Frontend", "JavaScript"],
  },
  {
    id: 4,
    title: "Data Science with Python",
    instructor: "Prof. David Kim",
    instructorAvatar: "/placeholder-pu62k.png",
    price: 94.99,
    originalPrice: 139.99,
    rating: 4.8,
    students: 9876,
    duration: "45 hours",
    level: "Intermediate",
    category: "Data Science",
    thumbnail: "/placeholder-eh269.png",
    description: "Comprehensive data science course covering pandas, numpy, visualization, and machine learning.",
    features: [
      "Pandas & NumPy mastery",
      "Data visualization",
      "Statistical analysis",
      "Machine learning basics",
      "Real datasets",
    ],
    curriculum: [
      { module: "Python Data Structures", duration: "5 hours" },
      { module: "Pandas for Data Analysis", duration: "12 hours" },
      { module: "Data Visualization", duration: "8 hours" },
      { module: "Statistical Analysis", duration: "10 hours" },
      { module: "ML with Scikit-learn", duration: "10 hours" },
    ],
    isAIRecommended: true,
    tags: ["Python", "Data Science", "Pandas", "Machine Learning"],
  },
  {
    id: 5,
    title: "Mobile App Development with React Native",
    instructor: "Alex Thompson",
    instructorAvatar: "/placeholder-9sya6.png",
    price: 84.99,
    originalPrice: 124.99,
    rating: 4.6,
    students: 5432,
    duration: "38 hours",
    level: "Intermediate",
    category: "Mobile Development",
    thumbnail: "/placeholder-5e9oe.png",
    description: "Build cross-platform mobile apps with React Native. From basics to app store deployment.",
    features: [
      "Cross-platform development",
      "Native device features",
      "Navigation & routing",
      "State management",
      "App store deployment",
    ],
    curriculum: [
      { module: "React Native Basics", duration: "6 hours" },
      { module: "Navigation & UI Components", duration: "10 hours" },
      { module: "Native Device APIs", duration: "8 hours" },
      { module: "State Management", duration: "6 hours" },
      { module: "Testing & Deployment", duration: "8 hours" },
    ],
    isAIRecommended: false,
    tags: ["React Native", "Mobile", "JavaScript", "Cross-platform"],
  },
  {
    id: 6,
    title: "Cloud Computing with AWS",
    instructor: "Jennifer Lee",
    instructorAvatar: "/placeholder-ftfvo.png",
    price: 109.99,
    originalPrice: 159.99,
    rating: 4.9,
    students: 7654,
    duration: "50 hours",
    level: "Intermediate",
    category: "Cloud Computing",
    thumbnail: "/placeholder-wviqa.png",
    description:
      "Master AWS cloud services, architecture patterns, and deployment strategies for scalable applications.",
    features: [
      "AWS core services",
      "Serverless architecture",
      "DevOps practices",
      "Security best practices",
      "Cost optimization",
    ],
    curriculum: [
      { module: "AWS Fundamentals", duration: "8 hours" },
      { module: "EC2 & VPC", duration: "10 hours" },
      { module: "Serverless with Lambda", duration: "12 hours" },
      { module: "Database Services", duration: "8 hours" },
      { module: "DevOps & CI/CD", duration: "12 hours" },
    ],
    isAIRecommended: true,
    tags: ["AWS", "Cloud", "DevOps", "Serverless"],
  },
]

export const categories = [
  "All Categories",
  "Web Development",
  "Machine Learning",
  "Frontend Development",
  "Data Science",
  "Mobile Development",
  "Cloud Computing",
]

export const levels = ["All Levels", "Beginner", "Intermediate", "Advanced"]

export const testimonials = [
  {
    id: 1,
    name: "John Smith",
    role: "Software Developer",
    avatar: "/placeholder-bplpu.png",
    content:
      "The AI-powered learning paths helped me master React in just 3 months. The personalized recommendations were spot on!",
    rating: 5,
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "Data Scientist",
    avatar: "/placeholder-c8xgv.png",
    content:
      "Best investment I've made in my career. The ML course was comprehensive and the AI tutor answered all my questions instantly.",
    rating: 5,
  },
  {
    id: 3,
    name: "Ahmed Hassan",
    role: "Full Stack Developer",
    avatar: "/placeholder-kdulb.png",
    content:
      "The hands-on projects and AI-generated quizzes made learning engaging. I landed my dream job after completing 3 courses here.",
    rating: 5,
  },
]

export const studentCoursesData = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    instructor: "Dr. Sarah Johnson",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.8,
    reviewCount: 2847,
    price: 89.99,
    originalPrice: 199.99,
    category: "Web Development",
    level: "Beginner",
    duration: "42 hours",
    lessons: 156,
    students: 15420,
    thumbnail: "/web-development-course.png",
    description:
      "Learn HTML, CSS, JavaScript, React, Node.js and more in this comprehensive bootcamp.",
    tags: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
    isEnrolled: true,
    progress: 65,
    isBestseller: true,
    lastUpdated: "2024-01-15",
    features: [
      "Master HTML, CSS, and JavaScript",
      "Build real-world projects",
      "Learn React and Node.js",
      "Understand responsive design",
    ],
    curriculum: [
      { module: "Introduction to Web Development", duration: "2 hours" },
      { module: "JavaScript Fundamentals", duration: "5 hours" },
      { module: "React Basics", duration: "4 hours" },
      { module: "Node.js and Backend Development", duration: "6 hours" },
    ],
    isAIRecommended: true,
  },
  {
    id: 2,
    title: "Machine Learning Fundamentals",
    instructor: "Prof. Mike Chen",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.9,
    reviewCount: 1923,
    price: 129.99,
    originalPrice: 249.99,
    category: "AI & ML",
    level: "Intermediate",
    duration: "38 hours",
    lessons: 124,
    students: 8750,
    thumbnail: "/machine-learning-course.png",
    description:
      "Master machine learning algorithms, neural networks, and deep learning concepts.",
    tags: ["Python", "TensorFlow", "Neural Networks", "Deep Learning"],
    isEnrolled: false,
    isBestseller: true,
    lastUpdated: "2024-01-20",
    features: [
      "Understand ML algorithms",
      "Implement neural networks",
      "Apply deep learning techniques",
      "Work with real-world datasets",
    ],
    curriculum: [
      { module: "Introduction to Machine Learning", duration: "3 hours" },
      { module: "Supervised Learning", duration: "5 hours" },
      { module: "Neural Networks", duration: "6 hours" },
      { module: "Deep Learning Projects", duration: "4 hours" },
    ],
    isAIRecommended: false,
  },
  {
    id: 3,
    title: "Advanced React Patterns",
    instructor: "Emma Wilson",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.7,
    reviewCount: 1456,
    price: 79.99,
    originalPrice: 159.99,
    category: "Frontend",
    level: "Advanced",
    duration: "28 hours",
    lessons: 89,
    students: 5230,
    thumbnail: "/react-patterns-course.png",
    description:
      "Learn advanced React patterns, hooks, context, and performance optimization.",
    tags: ["React", "Hooks", "Context", "Performance"],
    isEnrolled: true,
    progress: 85,
    isBestseller: false,
    lastUpdated: "2024-01-10",
    features: [
      "Master advanced React patterns",
      "Optimize React applications",
      "Use hooks and context effectively",
      "Build scalable components",
    ],
    curriculum: [
      { module: "Advanced Hooks", duration: "3 hours" },
      { module: "Context API", duration: "4 hours" },
      { module: "Performance Optimization", duration: "3 hours" },
    ],
    isAIRecommended: true,
  },
  {
    id: 4,
    title: "Data Science with Python",
    instructor: "Dr. Alex Rodriguez",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.6,
    reviewCount: 2156,
    price: 99.99,
    originalPrice: 199.99,
    category: "Data Science",
    level: "Intermediate",
    duration: "45 hours",
    lessons: 178,
    students: 12340,
    thumbnail: "/data-science-python-course.png",
    description:
      "Complete data science course covering pandas, numpy, matplotlib, and machine learning.",
    tags: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn"],
    isEnrolled: false,
    isBestseller: false,
    lastUpdated: "2024-01-18",
    features: [
      "Analyze data with Pandas and NumPy",
      "Visualize data with Matplotlib",
      "Build ML models with Scikit-learn",
      "Work on real-world data projects",
    ],
    curriculum: [
      { module: "Introduction to Data Science", duration: "4 hours" },
      { module: "Data Analysis with Pandas", duration: "6 hours" },
      { module: "Data Visualization", duration: "5 hours" },
      { module: "Machine Learning Basics", duration: "4 hours" },
    ],
    isAIRecommended: true,
  },
  {
    id: 5,
    title: "Mobile App Development with React Native",
    instructor: "John Smith",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.5,
    reviewCount: 987,
    price: 109.99,
    originalPrice: 219.99,
    category: "Mobile Development",
    level: "Intermediate",
    duration: "35 hours",
    lessons: 142,
    students: 6780,
    thumbnail: "/react-native-app-dev.png",
    description: "Build cross-platform mobile apps using React Native and Expo.",
    tags: ["React Native", "Expo", "Mobile", "Cross-platform"],
    isEnrolled: false,
    isBestseller: false,
    lastUpdated: "2024-01-12",
    features: [
      "Develop cross-platform mobile apps",
      "Use React Native and Expo",
      "Build real-world mobile projects",
      "Learn mobile UI/UX design",
    ],
    curriculum: [
      { module: "Introduction to React Native", duration: "3 hours" },
      { module: "Building UI with React Native", duration: "5 hours" },
      { module: "Expo Integration", duration: "4 hours" },
      { module: "Deploying Mobile Apps", duration: "3 hours" },
    ],
    isAIRecommended: false,
  },
  {
    id: 6,
    title: "UI/UX Design Masterclass",
    instructor: "Lisa Wang",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4.8,
    reviewCount: 1678,
    price: 89.99,
    originalPrice: 179.99,
    category: "Design",
    level: "Beginner",
    duration: "32 hours",
    lessons: 98,
    students: 9450,
    thumbnail: "/ui-ux-design-course-figma.jpg",
    description:
      "Learn UI/UX design principles, Figma, prototyping, and user research.",
    tags: ["Figma", "Prototyping", "User Research", "Design Systems"],
    isEnrolled: false,
    isBestseller: true,
    lastUpdated: "2024-01-22",
    features: [
      "Master UI/UX design principles",
      "Create prototypes with Figma",
      "Conduct user research",
      "Build design systems",
    ],
    curriculum: [
      { module: "Introduction to UI/UX", duration: "3 hours" },
      { module: "Figma Basics", duration: "4 hours" },
      { module: "Prototyping Techniques", duration: "3 hours" },
      { module: "User Research Methods", duration: "3 hours" },
    ],
    isAIRecommended: true,
  },
];